-- ------------------------------------------------------------------------------------------------------------------
-- Advanced — Subqueries, CTEs, Window Functions, Views 
-- ------------------------------------------------------------------------------------------------------------------

--  1.create a view called product_sales_summary that stores each product's total quantity sold and total revenue.
create view product_sales_summary as
select p.product_id,p.product_name,sum(o.quantity) as total_quantity,sum(o.total_amount) as total_revenue 
from products p join orders o on p.product_id = o.product_id
group by p.product_id,p.product_name
order by p.product_id;

select * from product_sales_summary;

-- ------------------------------------------------------------------------------------------------------------------

-- 2. Display top 3 products whose revenue is above the average product revenue
select * from product_sales_summary 
where total_revenue > ( select avg(total_revenue) from product_sales_summary)
order by total_revenue desc limit 3;

-- ------------------------------------------------------------------------------------------------------------------

-- 3. Find the products whose unit_price is greater than the average product price.
select product_name, unit_price from products
where unit_price > (select avg(unit_price) from products);

-- ------------------------------------------------------------------------------------------------------------------

-- 4. Find the products that belong to the Electronics or Books categories using a subquery.
select * from products where category in ( select category from products 
where category in ('electronics', 'books'));

-- ------------------------------------------------------------------------------------------------------------------
-- 5. find the customers who have placed orders in cities where sellers are located and 
-- whose total spending is greater than 25000. display the customer name and total spending.
select c.first_name,c.last_name, sum(o.total_amount) as total_spending 
from customers c join orders o on c.customer_id = o.customer_id
where o.city in ( select city from sellers)
group by c.customer_id, c.first_name,c.last_name
having sum(o.total_amount) > 25000;
-- ------------------------------------------------------------------------------------------------------------------
-- 6. Which products have generated more revenue than the average revenue generated by all products?
with product_revenue as (select p.product_id, p.product_name,sum(o.total_amount) as total_revenue
from products p join orders o on p.product_id = o.product_id
group by p.product_id, p.product_name)
select * from product_revenue where total_revenue > (select avg(total_revenue)from product_revenue);
-- ------------------------------------------------------------------------------------------------------------------
--  7. Find the top 3 customers based on their total spending
select customer_id, total_spending
from (select customer_id,sum(total_amount) as total_spending,
dense_rank() over(order by sum(total_amount) desc) as rnk
from orders group by customer_id) as t
where rnk <= 3;
-- ------------------------------------------------------------------------------------------------------------------

-- 8. find the ranking of sellers based on the total number of orders received for their products
select seller_id, seller_name, total_orders, dense_rank() over(order by total_orders desc) as seller_rank
from (select s.seller_id, s.seller_name,count(o.order_id) as total_orders 
from sellers s join products p on s.seller_id = p.seller_id
join orders o on p.product_id = o.product_id
group by s.seller_id, s.seller_name) as t;
-- ------------------------------------------------------------------------------------------------------------------
-- 9. Find the second-highest spending customer.
select customer_id,first_name,last_name,highest_spend from
(select c.customer_id, c.first_name,c.last_name,sum(o.total_amount) as highest_spend,
dense_rank() over (order by sum(total_amount) desc) as spending_rank
from customers c join orders o on c.customer_id = o.customer_id 
group by c.customer_id, c.first_name,c.last_name) as second_highest 
where spending_rank=2;

-- ------------------------------------------------------------------------------------------------------------------
-- 10. Create a procedure that accepts a customer ID and displays all orders placed by that customer. 
delimiter //
create procedure customer_orders(in cust_id varchar(20))
begin
    select *
    from orders
    where customer_id = cust_id;
end //
delimiter ;
call customer_orders('CUST2345');
-- ------------------------------------------------------------------------------------------------------------------
